import PDFDocument from 'pdfkit';

interface InvoiceData {
    invoiceNumber: string;
    status: string;
    issueDate: string | null;
    dueDate: string | null;
    currency: string;
    subtotal: number;
    tax: number;
    total: number;
    notes: string | null;
    contact: { name: string; email?: string; phone?: string; company?: string } | null;
    organization: { name: string } | null;
    items: { description: string; quantity: number; unitPrice: number; total: number }[];
}

export function generateInvoicePDF(invoice: InvoiceData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ size: 'A4', margin: 50 });
        const chunks: Buffer[] = [];

        doc.on('data', (chunk: Buffer) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        const BLUE = '#4A89B9';
        const ORANGE = '#FF5F00';
        const DARK = '#1e293b';
        const GRAY = '#475569';

        // Header
        doc.fontSize(24).fillColor(BLUE).text('DOMOT', 50, 50, { continued: true })
           .fillColor(ORANGE).text('AI');
        doc.fontSize(10).fillColor(GRAY).text(invoice.organization?.name || 'Domotai Technologies', 50, 80);

        // Invoice title
        doc.fontSize(28).fillColor(DARK).text('INVOICE', 350, 50, { align: 'right' });
        doc.fontSize(12).fillColor(GRAY).text(`#${invoice.invoiceNumber}`, 350, 85, { align: 'right' });
        doc.fontSize(10).text(`Status: ${invoice.status}`, 350, 102, { align: 'right' });

        // Dates
        let y = 130;
        doc.fontSize(10).fillColor(DARK);
        if (invoice.issueDate) {
            doc.text(`Issue Date: ${new Date(invoice.issueDate).toLocaleDateString()}`, 50, y);
            y += 16;
        }
        if (invoice.dueDate) {
            doc.text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`, 50, y);
            y += 16;
        }

        // Bill To
        if (invoice.contact) {
            y += 10;
            doc.fontSize(11).fillColor(BLUE).text('Bill To:', 50, y);
            y += 18;
            doc.fontSize(10).fillColor(DARK).text(invoice.contact.name, 50, y);
            if (invoice.contact.company) { y += 14; doc.text(invoice.contact.company, 50, y); }
            if (invoice.contact.email) { y += 14; doc.fillColor(GRAY).text(invoice.contact.email, 50, y); }
            if (invoice.contact.phone) { y += 14; doc.text(invoice.contact.phone, 50, y); }
        }

        // Items table
        y = Math.max(y + 40, 250);

        // Table header
        doc.rect(50, y, 495, 24).fill(BLUE);
        doc.fontSize(9).fillColor('#ffffff');
        doc.text('Description', 58, y + 7, { width: 220 });
        doc.text('Qty', 290, y + 7, { width: 60, align: 'center' });
        doc.text('Unit Price', 355, y + 7, { width: 80, align: 'right' });
        doc.text('Total', 445, y + 7, { width: 92, align: 'right' });
        y += 24;

        // Table rows
        const cur = invoice.currency || 'USD';
        for (const item of invoice.items) {
            const rowH = 22;
            const bgColor = invoice.items.indexOf(item) % 2 === 0 ? '#f8fafc' : '#ffffff';
            doc.rect(50, y, 495, rowH).fill(bgColor);
            doc.fontSize(9).fillColor(DARK);
            doc.text(item.description, 58, y + 6, { width: 220 });
            doc.text(String(item.quantity), 290, y + 6, { width: 60, align: 'center' });
            doc.text(`${Number(item.unitPrice).toFixed(2)}`, 355, y + 6, { width: 80, align: 'right' });
            doc.text(`${Number(item.total).toFixed(2)}`, 445, y + 6, { width: 92, align: 'right' });
            y += rowH;
        }

        // Totals
        y += 16;
        doc.fontSize(10).fillColor(GRAY);
        doc.text('Subtotal:', 370, y, { width: 70, align: 'right' });
        doc.fillColor(DARK).text(`${Number(invoice.subtotal).toFixed(2)} ${cur}`, 445, y, { width: 92, align: 'right' });
        y += 18;
        doc.fillColor(GRAY).text('Tax:', 370, y, { width: 70, align: 'right' });
        doc.fillColor(DARK).text(`${Number(invoice.tax).toFixed(2)} ${cur}`, 445, y, { width: 92, align: 'right' });
        y += 20;
        doc.rect(370, y - 2, 170, 24).fill(DARK);
        doc.fontSize(11).fillColor('#ffffff').text('Total:', 378, y + 4, { width: 60, align: 'right' });
        doc.text(`${Number(invoice.total).toFixed(2)} ${cur}`, 445, y + 4, { width: 92, align: 'right' });

        // Notes
        if (invoice.notes) {
            y += 50;
            doc.fontSize(10).fillColor(BLUE).text('Notes:', 50, y);
            y += 16;
            doc.fontSize(9).fillColor(GRAY).text(invoice.notes, 50, y, { width: 400 });
        }

        // Footer
        doc.fontSize(8).fillColor(GRAY)
           .text('Generated by Domotai CRM', 50, 760, { align: 'center', width: 495 });

        doc.end();
    });
}
